openapi: 3.1.0
info:
  title: Neo4j Cypher Query API
  version: 1.0.0
servers:
  - url: https://752afd5d.databases.neo4j.io/
paths:
  /db/neo4j/query/v2:
    post:
      summary: Run Cypher read-only query
      operationId: runCypher
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CypherQuery"
      responses:
        "200":
          description: Query result
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    CypherQuery:
      type: object
      properties:
        statement:
          type: string
        parameters:
          type: object
          additionalProperties: true
      required:
        - statement
